version: 2
jobs:
  build:
    machine: true
    working_directory: ~/workspace

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker-compose up -d

      - run: docker exec -it node bash

      - run: npm i yarn -g

      - restore_cache:
          keys:
          - node_modules-{{ .Branch }}-{{ checksum "package.json" }}

      - run: yarn install

      - run: exit

      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/

      - run: make deploy