version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:6.10.3

    steps:
      - checkout

      - restore_cache:
          keys:
          - node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: node_modules-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
      
      - run:
        name: docker
        command: docker pull redis:4.0.1-alpine

      - run: 
          name: deploy
          command: ls && make deploy