version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3

    steps:
      - restore_cache:
          keys:
          - dependencies-v1-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-v1-
        
      - run: 
          name: test
          command: echo 23ß