version: 2
jobs:
  build:
    machine: true
    working_directory: ~/workspace

    steps:
      - checkout

      - restore_cache:
          keys:
          - node_modules-{{ .Branch }}-{{ checksum "package.json" }}

      - run: docker-compose up -d

      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/

      - run: make deploy